FROM php:8.3-fpm-alpine

RUN apk add --no-cache \
  bash \
  git \
  curl \
  libzip-dev \
  oniguruma-dev \
  unzip

RUN docker-php-ext-install \
  pdo \
  pdo_mysql \
  mbstring \
  zip

WORKDIR /var/www

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

EXPOSE 9000
CMD ["php-fpm"]