services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/backend.prod.Dockerfile
      args:
        APP_NAME: Laravel
        APP_ENV: production
        APP_KEY: base64:mWzxDGFDYH/IwMWJys/lrXzCfI5akBXD0tCnbQ6UX3I=
        APP_DEBUG: true
        APP_URL: https://laravel.betocode.dev
    volumes:
      - laravel_code:/var/www/html
      - ./docker/php/prod.ini:/usr/local/etc/php/conf.d/prod.ini
    expose:
      - "9000"

  nginx:
    container_name: nginx
    image: nginx:1.27-alpine
    depends_on:
      - backend
    volumes:
      - laravel_code:/var/www/html:ro
      - ./docker/nginx/backend.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"

volumes:
  laravel_code:
