services:
  database:
    # container_name: mysql
    # image: mysql:8.0.45
    # ports:
    #   - "3306:3306"
    # environment:
    #   MYSQL_ROOT_PASSWORD: x
    #   MYSQL_DATABASE: laravel
    #   MYSQL_USER: beto
    #   MYSQL_PASSWORD: x
    # volumes:
    #   - mysql_data:/var/lib/mysql
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    container_name: postgres
    image: postgres:17.8-alpine3.23
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: beto
      POSTGRES_PASSWORD: x
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "beto", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./laravel:/var/www/html
      - backend_vendor:/var/www/html/vendor
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - database
    stdin_open: true
    tty: true

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - frontend_node_modules:/frontend/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  # mysql_data:
  postgres_data:
  backend_vendor:
  frontend_node_modules:
