services:
  database:
    container_name: mysql
    image: mysql:8.0.45
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: x
      MYSQL_DATABASE: laravel
      MYSQL_USER: beto
      MYSQL_PASSWORD: x
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./laravel:/var/www/html
      - backend_vendor:/var/www/html/vendor
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - database
    stdin_open: true
    tty: true

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - frontend_node_modules:/frontend/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  mysql_data:
  backend_vendor:
  frontend_node_modules:
