services:
  laravel:
    build:
      context: .
      dockerfile: docker/laravel/Dockerfile
      target: prod
    restart: always

  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - laravel
    volumes:
      - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`laravel.betocode.dev`)"
      - "traefik.http.routers.laravel.entrypoints=websecure"
      - "traefik.http.routers.laravel.tls.certresolver=letsencrypt"
      - "traefik.http.services.laravel.loadbalancer.server.port=80"